name: Build .NET MAUI Windows

on:
  push:
    tags:
      - 'windows-*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: dotnet restore
      - run: dotnet publish -f net7.0-windows10.0.19041.0 -c Release -p:WindowsPackageType=None -p:WindowsAppSDKSelfContained=true
      - uses: actions/upload-artifact@v4
        with:
          name: MekToolsReduxApp-${{github.ref_name}}
          path: 'MekToolsReduxApp\bin\Release\net7.0-windows10.0.19041.0\win10-x64\publish\'
          retention-days: 90