name: Build .NET MAUI Windows

on:
  workflow_dispatch:
    inputs:
      targetPlatform:
        description: 'Target Platform'
        required: true
        default: 'windows'
        type: choice
        options:
          - windows
        
jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: |
          echo "Platform chosen: PLATFORM"
        env:
          PLATFORM: ${{ inputs.targetPlatform }}
      - uses: actions/checkout@v3
      - run: dotnet restore
      - run: cd MekToolsReduxApp
      - run: dotnet publish -f net7.0-windows10.0.19041.0 -c Release -p:WindowsPackageType=None -p:WindowsAppSDKSelfContained=true